- .gitignore
- package-lock.json
- package.json
- scripts/build.js
added build script (utilizing esbuilt)
> reintroduced build script

- src/components/badge/README.md
- src/components/badge/badge-base.ts
BREAKING CHANGE: default slot removed
> refactor(badge): remove slot support

- config/rollup/rollup.config.base.ts
- docs/index.html
- package-lock.json
- package.json
- src/components/badge/badge.ts
> fix(build): delete dist only on first watch

- 11ty/_layouts/base.njk
> docs(workspace): update title and icon

- .eslintrc
- package-lock.json
- package.json
JSDoc warning aren't reflected as current script flags run as quiet
for the sake of isolating concern, it will be changed in following PRs
> style(eslint): add jsdoc plugin

- README.md
- package-lock.json
- package.json
- tools/generators/vivid-component/files/README.md__tmpl__
- tools/generators/vivid-component/files/__fileName__.spec.ts__tmpl__
- tools/generators/vivid-component/files/__fileName__.template.ts__tmpl__
- tools/generators/vivid-component/files/__fileName__.ts__tmpl__
- tools/generators/vivid-component/files/index.ts__tmpl__
- tools/generators/vivid-component/files/ui.test.ts__tmpl__
- tools/generators/vivid-component/index.spec.ts
- tools/generators/vivid-component/index.ts
- tools/generators/vivid-component/schema.d.ts
- tools/generators/vivid-component/schema.json
- tools/jest.config.js
- tools/jest.config.js.bak
- tools/tsconfig.tools.json
> chore(workspace): simple vivid component generator

- apps/docs/project.json
- libs/components/rollup.config.base.ts
> fix(docs): build works with implicit dependencies

- apps/docs/_includes/navigation.njk
- apps/docs/assets/styles/main.css
basic side nav style until we will have side nav
`<code>` tag styling
`table` styling
> fix(documentation): basic style

- apps/docs/_data/components.json
- change/@vonage-vivid-60014f32-b9ed-4828-bdd5-8b918a3ccf46.json
- libs/components/src/lib/breadcrumb/README.md
- libs/components/src/lib/breadcrumb/breadcrumb.spec.ts
> fix(docs): remove breadcrumb item from docs

- apps/docs/assets/styles/main.css
- change/@vonage-vivid-11fc3288-4c62-42d5-865f-cc25226210b3.json
- libs/components/src/lib/header/header.scss
- libs/components/src/lib/side-drawer/side-drawer.scss
- libs/components/src/lib/side-drawer/side-drawer.template.ts
- libs/components/src/lib/side-drawer/side-drawer.ts
- package-lock.json
- package.json
> fix(components): side drawer blocking elements

- apps/docs/_layouts/base.njk
Shape changed from pill to rounded as a followup of #657.
> fix(docs): hamburger button shape

- apps/docs/assets/scripts/viewport-handler.js
observing window resize rather then visual viewport improves user
experience
> refactor(docs): improve ux by window resize

- change/@vonage-vivid-d8a0b69b-edfe-43fc-a2fc-fcfe0e9e2ca0.json
- libs/components/src/lib/checkbox/checkbox.scss
- libs/components/src/lib/radio/radio.scss
made a mess in #737 , disregard it.
> fix(components): prevent checkbox & radio shrinking

- apps/docs/assets/scripts/main.js
Click on the copy button to see the change.
> feat(docs): change icon when copy from clipboard

- README.md
- apps/docs/assets/styles/main.css
- change/@vonage-vivid-81d59a1e-60f0-4ef1-acbc-eb5ad8638c38.json
- libs/components/README.md
> fix(docs): horizontal scroll in mobile main page

- apps/docs/assets/styles/iframe.css
...were broken by getting rid of quirks mode in #881
> fix(docs): samples vertical centering

- change/@vonage-vivid-6045aedd-b5ed-40d0-95bb-1e7131667501.json
- libs/components/src/lib/dialog/dialog.scss
Regardless the option to remove the slot altogether, this is needed. until decide otherwise regarding this slot
> fix(dialog): assign graphic slot to grid area

- .github/CONTRIBUTING.md
> chore(docs): update contributing guide

- change/@vonage-vivid-708607e0-8bda-4f42-88a9-f8ef88319131.json
no longer required as beachball is no longer in use
> chore(workspace): delete change folder

- libs/components/src/lib/tree-item/definition.ts
> fix(components): circular dependency in tree-item

- .github/workflows/lint-pr-title.yml
(the check is pretty lax, you can put the ref anywhere in the description part.)
> chore(ci): VIV-902 check for Jira ref in PR titles

- apps/docs/_data/components.json
> fix(doc): wrong dependency list for select (VIV-000)

- .github/workflows/lint-pr-title.yml
should fix #1135 because I'm dumb
> chore(ci): skip PR linting for dependabot (VIV-000)

- libs/components/src/lib/pagination/README.md
- libs/components/src/lib/pagination/pagination.spec.ts
- libs/components/src/lib/pagination/pagination.ts
Remove `vwc` prefix from event name
> chore(pagination): change event fix (VIV-000)

- package.json
this missing indentation made me feel bad (your code is so beautiful 😍 )
> fix(format): add missing indentation at package.json (VIV-000)

- libs/components/src/lib/audio-player/audio-player.spec.ts
- libs/components/src/lib/audio-player/audio-player.template.ts
- libs/components/src/lib/audio-player/audio-player.ts
- libs/components/src/lib/audio-player/locale.ts
- libs/components/src/lib/slider/slider.template.ts
- libs/components/src/lib/slider/slider.ts
- libs/components/src/locales/en-GB.ts
- libs/components/src/locales/en-US.ts
- libs/components/src/locales/ja-JP.ts
- libs/components/src/locales/zh-CN.ts
- libs/components/src/shared/localization/Locale.ts
- Adds translations for the internal labels
- Adds overrides for the labels so consumers can add their own versions
- Axe test passes
> chore: adds translated labels and overrides

- libs/components/metadata.json
- libs/components/src/lib/rich-text-editor/facades/prose-mirror-vivid.schema.ts
- libs/components/src/lib/rich-text-editor/facades/vivid-prose-mirror.facade.spec.ts
- libs/components/src/lib/rich-text-editor/facades/vivid-prose-mirror.facade.ts
- libs/components/src/lib/rich-text-editor/menubar/definition.ts
- libs/components/src/lib/rich-text-editor/menubar/menubar.scss
- libs/components/src/lib/rich-text-editor/menubar/menubar.spec.ts
- libs/components/src/lib/rich-text-editor/menubar/menubar.template.ts
- libs/components/src/lib/rich-text-editor/rich-text-editor.spec.ts
- libs/components/src/lib/rich-text-editor/rich-text-editor.template.ts
- libs/components/src/lib/rich-text-editor/rich-text-editor.ts
Internal implementation - a small step towards the goal
> chore(rich-text-editor): added setSelectionDecoration method on the facade (VIV-2370)

- libs/components/src/lib/audio-player/audio-player.spec.ts
- libs/components/src/lib/audio-player/audio-player.template.ts
According to spec, `Infinity` duration means the audio is streaming.
In this case, the audio only shows the progress time without a duration.
> feat(audio player): handle Infinity duration (VIV-2569)
