- change/@vonage-vivid-c321371a-c7b0-41ab-b9e3-4bddc6b11156.json
- libs/components/src/lib/badge/README.md
- libs/components/src/lib/badge/badge.scss
- libs/components/src/lib/badge/badge.spec.ts
- libs/components/src/lib/badge/badge.template.ts
- libs/components/src/lib/badge/badge.ts
- libs/components/src/lib/banner/banner.template.ts
- libs/components/src/lib/button/README.md
- libs/components/src/lib/button/button.scss
- libs/components/src/lib/button/button.spec.ts
- libs/components/src/lib/button/button.template.ts
- libs/components/src/lib/button/button.ts
- libs/components/src/lib/button/partials/_mixins.scss
- libs/components/src/lib/enums.ts
- libs/components/src/lib/popup/popup.template.ts
rename size (for block size members) to density due to its being a reserved name in input element
> refactor(components): rename size to density

- apps/docs/_layouts/base.njk
bug description:
1. click on dark-mode-toggle button to change theme 
2. click on a different page on the side-navigation
3. the theme resets back to the prev theme
> fix(docs): remove permanent from dark-mode-toggle

- change/@vonage-vivid-dbf94fe7-0778-4f8c-9311-8a04f662a5f2.json
- libs/components/src/lib/listbox-option/listbox-option.spec.ts
- libs/components/src/lib/listbox-option/listbox-option.template.ts
- libs/components/src/lib/listbox-option/listbox-option.ts
rename optionText property to text to align with components naming
convention
> fix(components): option align property with naming convention

- change/@vonage-vivid-637c6085-f498-42ba-802c-c22a83faa806.json
- libs/components/src/lib/calendar/calendar.spec.ts
followup of #913 
one of the tests is checking the result of `Intl.DateTimeFormat.format()` used to format an hour in AM/PM format against a hardcoded string.
the problem is that Intl seems to behave differently depending on the platform it is used in.
so far, experiments show that the character used to separate the hours number from the 'AM/PM' string is:
- a space in Chrome and Node pre-19
- a short non-breaking space in Node 19
this PR aims at making the test more resilient (and to stop failing on my machine)
(additionally, Chrome seems to output 'am/pm' on Mac and 'AM/PM' on Windows 😶)
> fix(calendar): brittle test character

- libs/components/src/lib/dialog/dialog.scss
- libs/components/src/lib/elevation/elevation.scss
Elevation adds background color and drop-down shadow filter and transition to its slotted item, causing component to change slotted items with position-fixed to be fixed to the new containing block (the component with elevation) and not the view-port.
In dialog showModal the filter is hidden by overflow-hidden therefor box-shadow was added.
The dialog box-shadow has hardcoded color and not variables because there's no need for color revert in darkmode.
> feat(elevation): moving style to :before pseudo element (VIV-1098)

- apps/docs/assets/scripts/icons-gallery.js
e.g. searching for "chevron" doesn't return any results
> fix(icons-gallery): add id array to the icons search (VIV-1139)

- apps/docs/_includes/navigation.njk
Everyone can see underlying nav
> fix(docs): underlying nav (VIV-000)

- apps/docs/code-example-preview/createCodeExample.js
When editing code this happens as the comment needs to be an html comment
> fix(docs): fix comment not being html comment (VIV-000)

- libs/wrapper-gen/src/generator/renderComponent.ts
Exposing methods via `ctx.expose` will not get them added to the emitted type definitions.
Therefore, they are now defined as `methods`
> fix(vue-wrappers): fix method types not emitted (VIV-1502)

- libs/components/vite.config.ts
As css is part included in the js bundle, it cannot be optimised later.
This change reduces bundle size of an empty Vue app from 748.78 kB -> 690.13 kB
> feat(components): minify css (VIV-1376)

- libs/components/src/lib/button/README.md
- libs/components/src/lib/button/button.template.ts
- libs/components/src/shared/patterns/affix.ts
Most buttons are announced as button now:
* `<vwc-button label="Click me"></vwc-button>` -> "Click me, button"
* `<vwc-button icon="icon" label="Click me"></vwc-button>` -> "Click me, button"
* `<vwc-button icon="icon" title="Click me"></vwc-button>` -> "Click me, button"
However, when using icon button with `aria-label` it is still announced as group:
* `<vwc-button icon="icon" aria-label="Click me"></vwc-button>` -> "Click me, group"
I don't think this can be easily fixed due to how our button works.
> fix(button): improve button accessibility (VIV-1505)

- libs/components/src/lib/alert/alert.scss
This change is meant to address https://github.com/Vonage/vivid-3/issues/1511 by adding a media query to set the `min-inline-size` to auto when the viewport is smaller than 768px. It still takes the `$alert-min-inline-size` in case the user wants to override this value.
> fix(alert): add media query to set min-inline-size to auto (VIV-1564)

- .github/workflows/_upload-coverage.yml
- .github/workflows/pull-request.yml
Finally figured out why the token was not being used which caused occasional failures when uploading coverage.
Now we get:
```diff
- ['info'] -> No token specified or token is empty
+ ['info'] ->  Token found by environment variables
```
> fix(ci): fix codecov token not being passed (VIV-000)

- libs/components/src/lib/date-range-picker/ui.test.ts
- libs/components/src/shared/patterns/form-elements/form-elements.spec.ts
- libs/components/src/shared/patterns/form-elements/form-elements.ts
- libs/components/src/shared/patterns/form-elements/message.scss
- libs/shared/src/lib/test-utils/index.ts
This can be tested by dynamically adding the `error-text` and the screen reader should announce it.
> fix(a11y): error message announcement in form elements (VIV-1593)

- libs/wrapper-gen/src/generator/ComponentDef.ts
- libs/wrapper-gen/src/generator/__fixtures__/componentDefs.ts
- libs/wrapper-gen/src/generator/__snapshots__/renderComponent.spec.ts.snap
- libs/wrapper-gen/src/generator/parseComponent.ts
- libs/wrapper-gen/src/generator/renderComponent.ts
Make Vue 3 behave like Vue 2 for boolean attributes. When `false`, attribute should be removed instead of set to `'false'`
> fix(vue-wrappers): fix handling of boolean attributes in Vue 3 (VIV-1898)

- libs/components/src/lib/selectable-box/selectable-box.spec.ts
- libs/components/src/lib/selectable-box/selectable-box.template.ts
When `clickable-box` is enabled, screen readers should announcement the control as a "toggle button".
This only happened when the box is checked. The reason is that the control had `aria-pressed="true"` set when it is checked but it is set to null when it is not checked, it should have been set to `false`.
> fix(selectable box): screen-reader accessibility when box is clickable (VIV-000)

- libs/components/src/lib/radio/radio.form-associated.ts
- libs/components/src/lib/radio/radio.spec.ts
- libs/components/src/lib/radio/radio.ts
- package-lock.json
The spec says the following:
- Radio with a `name` property should be validated for required
- Radio with a `name` in a group should be validated for required with all siblings of the same `name` such that if one of them is checked, required is satisfied and then `validity.valueMissing` should be false.
> fix(radio): radio required validation sync with spec (VIV-2265)

- libs/nx-vivid/src/generators/component/files/__fileName__.scss__tmpl__
- libs/nx-vivid/src/generators/component/files/__fileName__.spec.ts__tmpl__
- libs/nx-vivid/src/generators/component/files/__fileName__.template.ts__tmpl__
- libs/nx-vivid/src/generators/component/files/definition.ts__tmpl__
Now passes all tests and lintings (except e2e, which needs to generate snapshots)
> chore(nx-vivid): update the component generator template (VIV-000)

- libs/components/src/lib/rich-text-editor/facades/vivid-prose-mirror.facade.ts
- libs/components/src/lib/rich-text-editor/rich-text-editor.spec.ts
- libs/components/src/lib/rich-text-editor/rich-text-editor.ts
Should now allow to select and sync backward selection (Shift + Arrowleft keys)
> chore(rich-text-editor): fix selection reset on user selection (VIV-2435)

- libs/components/metadata.json
- libs/components/src/lib/rich-text-editor/facades/prose-mirror-vivid.schema.ts
- libs/components/src/lib/rich-text-editor/facades/vivid-prose-mirror.facade.spec.ts
- libs/components/src/lib/rich-text-editor/menubar/definition.ts
- libs/components/src/lib/rich-text-editor/menubar/menubar.scss
- libs/components/src/lib/rich-text-editor/menubar/menubar.spec.ts
- libs/components/src/lib/rich-text-editor/menubar/menubar.template.ts
- libs/components/src/lib/rich-text-editor/rich-text-editor.spec.ts
- libs/components/src/lib/rich-text-editor/rich-text-editor.template.ts
- libs/components/src/lib/rich-text-editor/rich-text-editor.ts
Notice that the `monospace` icon is currently not present and will appear once it will be added to the icon repo.
> chore(rich-text-editor): text decoration buttons active in the menubar (VIV-2370)

- apps/docs/assets/scripts/live-sample.js
- apps/docs/assets/scripts/visual-tests/visual-tests-utils.ts
- apps/docs/code-example-preview/createCodeExample.js
- apps/docs/content/playground.html
- apps/docs/libraries/markdown-it-fence.js
- apps/docs/variables-preview/index.js
This changes the file names for code examples from something like `/frames/cbd-code-block-<random number>.html` to `/frames/components-accordion-1.html` to make them stable between eleventy runs
> chore(docs): improve example names (VIV-000)
